### ISSUE TITLE
Please check in your dependencies

### ISSUE THREAD

**Issue by gracenoah** [abice/go-enum#12]
Your package is not go-get-able if you don't check in your vendor directory. This is what happens right now if I try to go get your package:

```
go get github.com/abice/go-enum
# github.com/Masterminds/sprig
../../Masterminds/sprig/crypto.go:35:37: multiple-value uuid.NewV4() in single-value context
```

**Comment by abice** [comment]
I just tested this this morning, and have no problems doing a `go get -v github.com/abice/go-enum` under a fresh golang:1.10 docker container.

It looks like the latest version of Masterminds/sprig has been updated to use `github.com/google/uuid` instead of `github.com/satori/go.uuid`.  Maybe try doing a `go get -u github.com/Masterminds/sprig` and see if that changes anything.  I'll definitely update my Gopkg.toml and lock to make sure they are referencing the new version.

If it happens again that one of the dependencies breaks, then I'll add the vendor directory, but I really don't want to have to do that.

Let me know if that helped at all.

**Comment by gracenoah** [comment]
Yep, it does work now. In general, I think this is more of an issue with `go get` in that it should respect your Gopkg.lock, but I know that go tools haven't been integrated with package management yet, so that's why it gets the latest versions of everything every time.

I guess, in the case of upstream versions becoming incompatible, the workaround in general would be to clone your repo, `dep ensure`, then `go install .`. That would be the only way to guarantee that your required dependency versions are actually respected. If you wanted them to be respected by `go get`, unfortunately, the only way seems to be to check in your vendor directory.

**Comment by abice** [comment]
Yeah, too true about that.  I personally am not a fan of checking in my vendor directory, but as this is a standalone tool, I have 2 options... 1 would be to check in the vendor directory, the other would be to provide precompiled binaries for people to install, and possibly a homebrew script.  I'm not at either point yet though.  I'll keep an eye out for any other breaking changes.
