### ISSUE TITLE
Sanitising EnumValue.Name

### ISSUE THREAD

**Issue by proglottis** [abice/go-enum#15]
I'm parsing an xml file format that has a lot of different enumerations and have been using go-enum with quite good success. I'm wondering if you would accept a pull request to tidy up EnumValue.Name even more?

Specifically I would like to strip out some common separators that are invalid in go identifiers like `-`

Currently EnumValue.Name is run through strings.Title, I think it would be relatively trivial to also strip out non-go-identifier characters at the same time.

**Comment by abice** [comment]
Sorry for the late response... I'm not against any pull requests, however I'm curious about your use case.  Are you saying that the enum that you are using has a `-` in the name like if `Mercedes` was actually `Mercedes-Benz`?  Probably would be a good addition.  If you already have one ready, go ahead and submit, otherwise I can get probably to it sometime this week.
