### ISSUE TITLE
Support option to override generated file suffix

### ISSUE THREAD

**Issue by michinger** [abice/go-enum#216]
First of all thanks so much for creating and maintaining this great tool!

I hope I did not just overlook this in the docs but it would be nice to have the option to change the suffix of the generated files.

So instead of `<filename>_enum.go`  being able change the pattern to `<filename>_enum_gen.go`

Maybe via an `--output-suffix` flag.

**Comment by abice** [comment]
I'm always glad to hear that people enjoy the tool!

You did not overlook that feature, no.  That sounds like a reasonable request, but my life is a bit crazy at the moment, so it _might_ be faster for you to submit a PR for that functionality.  I would be up for adding an output-suffix flag, and letting that change the `_enum.go` to whatever you need in that call.  If you have the time, contributions are always welcome.  Otherwise, I will try to get to it soon™
