### ISSUE TITLE
Input files flag should support file globbing

### ISSUE THREAD

**Issue by kroppt** [abice/go-enum#48]
I want to be able to slap all my enumerations into a single folder and use a file like `gen.go` to generate them. Perhaps there's something I'm missing regarding generation. But the best idea I had was to use file globbing to select all the files in the current folder for the tool. However, it does not appear to support it.

```
go-enum started. file: *.go
2021/03/09 15:16:59 failed generating enums
InputFile=C:\path\to\project\enums\*.go
Error=generate: error parsing input file 'C:\path\to\project\enums\*.go': open C:\path\to\project\enums\*.go: The filename, directory name, or volume label syntax is incorrect. 
project\enums\gen.go:1: running "go-enum": exit status 1
```

**Comment by abice** [comment]
I think I understand what you're asking, but can you elaborate on the `gen.go` comment?  I don't understand what that means.  Are you creating a file named `gen.go` that has all of your enums defined in them?  

Generally speaking I've either done `go:generate` from the source file, or used a Makefile to specify each file that's supposed to be generated (where you could easily use wildcard expansion).

I'll definitely investigate adding glob support, because I think that it's a reasonable request, but would definitely like to know more about what you're trying to do so that I don't miss the mark.

Thanks!

**Comment by kroppt** [comment]
By `gen.go` I just meant that there would be one file with the one generate comment for the whole folder, like how a `doc.go` file is used for just providing documentation for a package.

For now I have it the normal way, with one line per file. But with over 10 or 20 files, it will become cumbersome to edit every file to for example add a a command line option for each. Using a Makefile is a good idea too, but I currently don't use one.

The solution I had in mind was that each file specified on the command line would be glob checked. Because I organized the enums into one folder, I want to use `*.go` to select every file in the folder.
