### ISSUE TITLE
Mapping enums to aliases/symbols

### ISSUE THREAD

**Issue by charlieparkes** [abice/go-enum#52]
I have a lot of enums which need to be mapped to arbitrary strings that don't match the enum name. Am I missing a good way to handle this in the library already?

Would you be open to a PR adding optional mapping to symbols/aliases?

```
var _{{.enum.Name}}Symbols = map[string]{{.enum.Name}}{
{{- $vars := dict "lastoffset" 0 -}}
{{ range $rIndex, $value := .enum.Values }}
	{{- $lastOffset := pluck "lastoffset" $vars | first }}{{ $offset := sub $value.Value $rIndex }}
	{{- if $value.Comment}}
	"{{$value.Comment}}": {{$rIndex}},
	{{- end}}
{{- end}}
}

func Parse{{.enum.Name}}Symbol(bs []byte) ({{.enum.Name}}, error) {
    s := string(bs)
	if s == " " {
		s = "SPACE"
	}
	if val, ok := _{{.enum.Name}}Symbols[s]; ok {
		return val, nil
	}
	return {{.enum.Name}}(0), fmt.Errorf("'%s' is not a valid {{.enum.Name}}", string(bs))
}
```

```golang
/*
ENUM(
AlphaNumeric // A/N
Numeric // N
Misc // SPACE
)
*/
type FieldType int
```

```golang
var _FieldTypeSymbols = map[string]FieldType{
	"A/N":   0,
	"N":     1,
        "SPACE": 2,
}

func ParseFieldTypeSymbol(bs []byte) (FieldType, error) {
	s := string(bs)
	if s == " " {
		s = "SPACE"
	}
	if val, ok := _FieldTypeSymbols[s]; ok {
		return val, nil
	}
	return FieldType(0), fmt.Errorf("'%s' is not a valid FieldType", string(bs))
}
```

**Comment by abice** [comment]
I'm not sure I've come across a need like this... do you have an example of how you might handle this type of situation in another language that natively supports enums (c#, java, etc...)?  Would help me determine the best course of action for handling this scenario.

Off hand, I would say, this doesn't sound like a shortcoming of the enum package... perhaps you can have an `FieldTypeAlias` and do 2 parses for a value?  Another option is to add other custom logic outside of the code generation to handle these extra mappings.  I know it's not a great answer, but since the generator adds code to a separate file, there's nothing stopping you from adding more methods to the file the enum is defined in.

The problems I see with adding something like this in a generic manner are:
1) do you support only 1 alias
2) What you show in your example would interfere with the ability to add a comment to an enum value.

**Comment by charlieparkes** [comment]
I struggled with the same questions. My initial attempt was to create a generator with my own "assets", but that ran into issues because a few necessary functions are private.

Instead of adding a bunch of complexity that's specific to my use-case, would you be open to a PR adding something like `func NewGeneratorFromTemplate(t *template.Template) *Generator`? Then I could generate my own template assets and use the rest of go-enum as is.

**Comment by abice** [comment]
I have already been contemplating letting people specify their own templates to include, so would be open to a PR for that... Not necessarily override the default, but you can add ones either from a directory or file at a time if you want.

And just iterate through the templates and generate with the same input values as the current one.

Can add a flag to override default one I suppose, but additional ones only would be preferred starting point

**Comment by charlieparkes** [comment]
I've opened a PR that allows you to pass additional template file names (using Template.ParseFiles()).
