### ISSUE TITLE
Rerunning removes version information

### ISSUE THREAD

**Issue by WesDowney** [abice/go-enum#95]
Example go generate command in the enum file: `go:generate go-enum -f=$GOFILE --names --nocase --noprefix --prefix=Sample`

Rerunning `go generate ./...` when there are no changes in that file provides a diff that wipes from of the go-enum metadata. Here is the diff:

```// Code generated by go-enum DO NOT EDIT.
-// Version: 0.4.0
-// Revision: 7e2e8bcd629be550028ecfcdc51cc0199ca124ad
-// Build Date: 2022-03-21T16:28:18Z
-// Built By: goreleaser
+// Version:
+// Revision:
+// Build Date:
+// Built By:

**Comment by abice** [comment]
@WesDowney Are you able to share more information around your build process?  As it stands, it _looks_ like the second time the generate command is run, it's using a locally built version of go-enum, rather than a released binary.

If you're able to share, please do, as it would really help me track down the problem.

Thanks!

**Comment by abice** [comment]
Since I haven't heard back from you, I'm gonna go ahead and close this ticket.  I have no way to reproduce the issue at hand.  Feel free to either comment on this, or open a new ticket with more information for me to work with.

Thanks!
